Xray rails secure
hexagonalconsulting/xray-rails pull request #1
Opened 2017-12-01 17:26 UTC by this-miguel

@dlupu  these are the commits I have until now, please let me know what you think. Next I check which of their test I broke.

2017-12-01 17:29 UTC, dlupu requested changes

2017-12-01 17:29 UTC, dlupu commented on app/assets/javascripts/xray.js.coffee
> +  $.ajax(url: "/system_settings/file_editor?file=#{path}")
no ajax call, simply open in a new tab

2017-12-02 05:24 UTC, this-miguel commented
Hello @dlupu this commit ca2b687de7e5a5e17727741c412ad68c61f31ea2 deletes a section related to the Xray settings (that were ralated to change the editor in the configuration file using a UI, we are removing the capability to use that config file and the editor). After removing that related code all test are passing.

2017-12-20 11:23 UTC, dlupu approved these changes

2017-12-20 11:24 UTC, merged